apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: via-tabloid-spring-boot
  name: via-tabloid-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: via-tabloid-spring-boot
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: via-tabloid-spring-boot
    spec:
      containers:
        - env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: via-tabloid-secrets
                  key: DB_PASSWORD
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: via-tabloid-secrets
                  key: DB_URL_DOCKER
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: via-tabloid-secrets
                  key: DB_USERNAME
          image: via-tabloid-spring-boot:latest
          imagePullPolicy: Never
          name: via-tabloid-spring-boot
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
